Fix for ReadComicsOnlineTo
Paperback-iOS/extensions-promises pull request #160
Opened 2021-03-29 17:38 UTC by Aur0raN

Fixed Search Requests showing Comic Chapters instead of a single manga tile and some comics being incorrectly parsed.
Bumped version to 1.0.2

Fixed issues posted as images below: 

![image](https://user-images.githubusercontent.com/43220439/112876753-82b7ed80-90e3-11eb-9814-8d268b11cd04.png)
![image](https://user-images.githubusercontent.com/43220439/112876775-89defb80-90e3-11eb-91c1-52d77166cf63.png)

2021-03-29 18:00 UTC, ConradWeiser requested changes

2021-03-29 18:00 UTC, ConradWeiser commented on src/ReadComicsTo/Parser.ts
> +          let id = ($('a'), $('.bigChar').attr('href')?.replace('/Comic/', '')) ?? ''
Please ensure that if this `id` field is undefined (or in this case, an empty string) that you do not return a manga. Return an empty array.

2021-03-29 18:36 UTC, Aur0raN commented on src/ReadComicsTo/Parser.ts
> +          let id = ($('a'), $('.bigChar').attr('href')?.replace('/Comic/', '')) ?? ''
Change added

2021-03-31 04:17 UTC, ConradWeiser approved these changes

2021-04-02 20:29 UTC, merged