Add Readm
Paperback-iOS/extensions-promises pull request #162
Opened 2021-03-30 21:51 UTC by TheNetsky

Might need a quick look before merging. :)

2021-03-30 22:30 UTC, AdrienSeon requested changes
Some quick changes that I saw at first glance, did not check locally by cloning your repo though, just visually in the review.

2021-03-30 22:30 UTC, AdrienSeon commented on src/Readm/Readm.ts
> +          ids: updatedManga.ids
createMangaUpdates() needed here
```suggestion
          createMangaUpdates({ ids: updatedManga.ids });
```

2021-03-30 22:30 UTC, AdrienSeon commented on src/Readm/ReadmParser.ts
> +      else loadMore = false;
else is paired with the wrong if
```suggestion
    if (mangaTime > time) {
      if (ids.includes(id)) {
        updatedManga.push(id);
      }
    } else { 
      loadMore = false;
    }
```

2021-03-30 22:30 UTC, AdrienSeon commented on src/Readm/ReadmParser.ts
> +  search = search.replace(/im/i, "I'm");
Did not understand this line ?
Maybe it is a work in progress ?

2021-03-30 22:30 UTC, AdrienSeon commented on src/Readm/ReadmParser.ts
> +}
after page 6 on popular manga, the last button is no more, the check will then say true even if it's not the last page https://readm.org/popular-manga/7
Didn't check latests

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/Readm.ts
> +        url: `${RM_DOMAIN}/latest-releases/${page++}`,
Wouldn't that be `++page`? 
- ++page will increment the `page` value and return the new state
- page++ will increment the `page` value and return the PREVIOUS state.

This looks fine to me

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +    desc: description!,
Please try to avoid `!` marks. They used to crash the app if they were null for some reason. Now it may be alright, but it's good form to ensure that you're returning data when it's expected to be there. 

I see you colaless this to an empty string on line 13, is the `!` needed?

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      chapNum: Number(chapterNumber),
If by chance `chapterNumber` isn't a number, this will fail and potentially cause problems. 
Can you ensure that it's able to be cast to a number before doing this? Otherwise you'll be sending `NaN`'s back.

It's your call what to do if that case ever comes up. You can not include the chapter in the response array for instance. That kind of logic should be fine, since it never should occur if all goes well. It's just a 'just in case' kind of logic. (Say they change the website structure or something)

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      else loadMore = false;
What he's got here 'technically' might work, but as a coding convention, the suggestion is much nicer.

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      image: image!,
Try to avoid the use of `!`
If the ID is empty, or the image is empty, you may want to simply not push it to the `hotMangaUpdate` array

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      image: image!,
Reference the comment above

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      image: image!,
Reference the comment above

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      image: image!,
Reference the comment above

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +  for (const section of sections) sectionCallback(section);
Just a suggestion here, why not do the callback IMMEDIATELY after you've parsed the section? Since the callback is async, the application will be able to load in the data as it comes. 

This way, one section might be displaying, by the time the second section is done parsing. It's a little nicer for the user.

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +  search = search.replace(/im/i, "I'm");
It's a regular expression. 
`/im/i` searches for the word 'im' where the /i means that it's case insensitive. It replaces it with `I'm`. I'm sure there's a reason for this, otherwise why would it be here?

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      manga.push(createMangaTile({
Are you sure you want to push a manga tile if the ID is "" or the image is ""?

2021-03-31 01:46 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      manga.push(createMangaTile({
See the comment above

2021-03-31 06:53 UTC, TheNetsky commented on src/Readm/ReadmParser.ts
> +  search = search.replace(/im/i, "I'm");
This was originally for another source, however the issue where "Im" resulted in 0 results while "I'm" did give some results did happen on some other sources as well. I'm not sure if this is needed for this particular source. However I think it's a nice QoL thing to have imo.

2021-03-31 07:12 UTC, TheNetsky commented on src/Readm/ReadmParser.ts
> +      manga.push(createMangaTile({
I have seen manga on the site with a broken/no image cover URL, but it has chapters and works just fine. But yeah I shouldn't push the manga if no title/id is present. :)

2021-03-31 07:34 UTC, TheNetsky commented on src/Readm/ReadmParser.ts
> +      manga.push(createMangaTile({
However I took Manganelo as reference material, Manganelo doesn't seem to do this check either.

2021-03-31 08:30 UTC, AdrienSeon commented on src/Readm/Readm.ts
> +        url: `${RM_DOMAIN}/latest-releases/${page++}`,
Didn't know about this, thank you for your correction.

2021-03-31 23:01 UTC, AdrienSeon reviewed
Last tidbits, other than that it's good to go on my end !

2021-04-01 05:41 UTC, TheNetsky commented on src/Readm/ReadmParser.ts
> +    if (!id || !title) continue;
I don't really understand this one, the app will not fallback to it's "grey icon" when there's no valid image url provided? Because I've seen plenty of instances of manga covers with invalid imageURLS or no images at all. However the rest of the page is just fine as well as the chapters. I think it's kind of weird to void the whole manga just because the cover isn't loading?

2021-04-01 05:43 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      manga.push(createMangaTile({
A lack of image is fine then, at least ensure an ID

2021-04-01 05:44 UTC, TheNetsky commented on src/Readm/ReadmParser.ts
> +      chapNum: chapterNumber,
I haven't had an issue with this before? I've had it just show up as Chapter "NaN". However I haven't seen any errors because of this. Wouldn't it be better for the user that the user to know the chapter number is invalid instead of place a 0 on it?

2021-04-01 05:44 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +    if (!id || !title) continue;
The app should fallback to the grey cover. Having an image is preferred, but not required.

2021-04-01 06:32 UTC, AdrienSeon commented on src/Readm/ReadmParser.ts
> +      chapNum: chapterNumber,
@ConradWeiser do you know if paperback handles NaN ?
What will happen if the chapter is not a number app side ?

2021-04-01 06:35 UTC, ConradWeiser commented on src/Readm/ReadmParser.ts
> +      chapNum: chapterNumber,
I wouldn’t rely on the app being able to handle a NaN until Stateful is released with 0.6, best be safe until then and check source side.

if you are confident that it’ll not happen, it’s probably fine to omit for now, as the next update should make this issue a lot less critical

2021-04-01 20:35 UTC, closed without merging