[Webtoons] - Initial Implementation
Paperback-iOS/extensions-promises pull request #251
Opened 2021-05-16 18:01 UTC by ConradWeiser

Manga Updates is not available

2021-06-07 18:57 UTC, ConradWeiser commented
Searches do not work if there are spaces.
`" "` --> `"%20"` needs slapped in there for search titles.

2021-06-19 14:33 UTC, nar1n requested changes

2021-06-19 14:33 UTC, nar1n commented on src/Webtoons/Webtoons.ts
> +      url: `${WEBTOON_DOMAIN}/en/search?keyword=${query.title}`,
```suggestion
      url: `${WEBTOON_DOMAIN}/en/search?keyword=${query.title?.replace(/ /g, '%20')}`,
```

2021-06-20 13:07 UTC, nar1n approved these changes

2021-06-24 16:35 UTC, ConradWeiser commented
It's been reported that all Orig. series show as 'Completed' even if that's not the case. Something to look into.
Uses: `    const completed = $("span.txt_ico_completed2") === undefined ? MangaStatus.ONGOING : MangaStatus.COMPLETED;`

Targets: 
![image](https://user-images.githubusercontent.com/9699789/123300577-90f18c00-d4cf-11eb-9a0c-a5ed56e9c186.png)

2021-06-26 10:00 UTC, nar1n approved these changes

2021-06-26 10:40 UTC, nar1n requested changes

2021-06-26 10:40 UTC, nar1n commented on src/Webtoons/WebtoonsParser.ts
> +    const completed = $("span.txt_ico_completed2") === undefined ? MangaStatus.ONGOING : MangaStatus.COMPLETED;
```suggestion
    const completed = $("p.day_info").text().includes('COMPLETED') ? MangaStatus.COMPLETED : MangaStatus.ONGOING;
```
Tested and this works

2021-06-26 10:40 UTC, nar1n commented on src/Webtoons/WebtoonsParser.ts
> +const completed = $('span.txt_ico_completed2') === undefined ? MangaStatus.ONGOING : MangaStatus.COMPLETED
```suggestion
const completed = title.toLowerCase().includes('completed') ? MangaStatus.COMPLETED : MangaStatus.ONGOING
```
Completed manhwa are marked in title

2021-06-26 12:43 UTC, nar1n approved these changes

2021-06-26 12:48 UTC, TheNetsky approved these changes

2021-06-26 17:31 UTC, merged