Updated Manganelo's Rebranding to Manganato
Paperback-iOS/extensions-promises pull request #261
Opened 2021-05-30 10:59 UTC by nar1n

- Based on @TheNetsky 's [branch](https://github.com/TheNetsky/extensions-promises/tree/stable/src/Manganelo)
- Updated to use the new base url for new id while relying on redirecting for old urls
- New mangaId are of format `manga-hu985203` where as the old id are simply `zt922734`
- Is backwards compatible with old ids
- Still doesn't fix issues where some manga like `manga-kg987863` crashes the app

2021-05-31 09:12 UTC, TheNetsky approved these changes
Works good, expect for those specific mangas as described [here](https://github.com/Paperback-iOS/extensions-promises/issues/257#issuecomment-849135447) but besides that is seems to work smoothly!

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/Manganelo.ts
> +      newMangaId = await this.getNewMangaId(mangaId)
`await this.getNewMangaId(mangaId)` has the possibility where it might return an empty string.
Setting a mangaId to an empty string is not allowed. 

Throw an error with a relevant message if this is the case. You can either do that here, or you can keep it clean and throw the error in the `getNewMangaId(..)` function.

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +  const author = $("i.info-author").parent().next().text().replace(/\s-\s/g, ", ").trim();
According to https://cheerio.js.org/classes/node.html#next
Both `.next()` and `.parent()` can possibly return null. The typings don't seem to be included in the Cheerio library, though I suspect the document is correct given that you can't always guarantee that there's a parent node, or a in-line next node. 

This is probably fine here, this is merely context for why I've suggested more null colalessing in the `createManga({..})` return statement.

Null reference exceptions are a pain to figure out when they show up in the logs. Lets avoid that~

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +    author: author,
```suggestion
    author: author ?? "",
```

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +    desc: description,
```suggestion
    desc: description ?? "",
```

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +    artist: author,
```suggestion
    artist: author ?? "",
```

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +      image: image,
Image can return an empty string here. I saw you have a image URL for 'no thumbnail' or whatever, potentially include that here too! Don't return empty if you can avoid it.

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +      image: image,
Can return an empty string. Either stub image it, or don't return this object.

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +      image: image,
Image can return an empty string, see the above two cases

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +      image: image,
Image can return an empty string, avoid this. Put your own image in, or don't return this obj

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +      image: image,
Image can be an empty string

2021-06-01 15:55 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +    total = (/(\d+)/g.exec(total) ?? [''])[0];
This isn't a comment requesting a change. This line made me chuckle though.

2021-06-01 15:57 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +  const author = $("i.info-author").parent().next().text().replace(/\s-\s/g, ", ").trim();
As an ammendum to this, I'm not certain if colalessing this later will work. If `.parent()` returns null, and you attempt to do a `.next()` on it, it might fail there and not feed `author` a null value. 

For now, this might be fine. Just keep that in mind just in case Manganelo gets some really weird crashes with very little information 4 months from now.

2021-06-03 16:43 UTC, ConradWeiser requested changes
As a general note, I see you've got semicolons somewhere, but not everywhere. There's no consistency. Not really a blocker.

Looking much better! Only a few more things I've noticed with this visual pass. Thanks for the work!

2021-06-03 16:43 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +    const id = $("a", chapter).attr('href')?.split('/').pop() ?? "";
ID can be `""`
You do not ensure that there is an ID before you push this chapter to the list.

Catch this case, and do either a `continue` or throw an error if that's somehow an issue.

2021-06-03 16:43 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +    if (!image) image = $(p).attr("data-src") ?? "";
`image` is still potentially `""` even after this second check. Do a third check. If it's still empty, throw an error with a comment saying what happened.

2021-06-03 16:43 UTC, ConradWeiser commented on src/Manganelo/ManganeloParser.ts
> +        updatedManga.push(id);
`id` can be `""` here. If that's the case, don't push it to the updatedManga list.

2021-06-03 17:18 UTC, TheNetsky commented
The update section needs a bit of a closer look once we're re-enabling it. (After migration)

2021-06-03 21:44 UTC, ConradWeiser approved these changes
Lovely

2021-06-04 15:11 UTC, Aur0raN approved these changes
Tested on netsky's repo, works fine!

2021-06-04 15:14 UTC, merged