Support for Hachirumi
Paperback-iOS/extensions-promises pull request #285
Opened 2021-06-30 10:50 UTC by Curstantine

Had to reopen a pull....(⌒_⌒;)

2021-07-04 14:13 UTC, ConradWeiser requested changes
- Pages load kinda slowly though that's not really something you can do much about. I don't think it's enough to require a 'slow' tag on the source, so this is fine!
- Your descriptions should have some additional parsing work, see below

2021-07-04 14:13 UTC, ConradWeiser commented on src/Hachirumi/Hachirumi.ts
> +      desc: result.description,
Descriptions are read correctly, however they do not render all too well in the app. Take for example https://hachirumi.com/read/manga/love-cute-short-stories/

The description for this renders with a lot of HTML tags. `<a href=...>` `<img src=...>` etc.
These obviously don't render inside of the app.

I understand that the source doesn't really have many proper descriptions. I have a few suggestions:
- Either remove descriptions entirely and replace it with a static "Hachirumi does not provide descriptions"
- Parse out all of the HTML tags, grab the relevant information, and try to format it in a way which looks fine. Perhaps keep the HTML tag `text`, just get rid of the tags themselves?

2021-07-04 14:15 UTC, ConradWeiser commented
![EFA28244-6811-483B-A2F0-09EAD909E1FF](https://user-images.githubusercontent.com/9699789/124388396-c86eee00-dcb0-11eb-9d2b-8dd3cc53a11d.jpeg)

example

2021-07-11 21:19 UTC, ConradWeiser approved these changes
Looks solid to me! Tests and works without issue

2021-07-12 09:26 UTC, nar1n approved these changes

2021-07-12 09:26 UTC, merged